# Generated by Django 3.1.2 on 2020-10-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(max_length=5, verbose_name='Тип телефонного номера')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('phone_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello_world.phonetype', verbose_name='Тип телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Persone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='ФИО')),
                ('phones', models.ManyToManyField(to='hello_world.Phone', verbose_name='Телефоны')),
            ],
        ),
    ]
