# Generated by Django 3.1.2 on 2020-10-18 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello_world.phonetype', verbose_name='Тип телефона'),
        ),
        migrations.CreateModel(
            name='Persone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='ФИО')),
                ('phones', models.ManyToManyField(to='hello_world.Phone', verbose_name='Телефоны')),
            ],
        ),
    ]
