# Generated by Django 3.1.2 on 2020-10-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('description', models.TextField(blank=True, null=True, verbose_name='About Author')),
            ],
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=30, verbose_name='Title of the Series')),
                ('description', models.TextField(blank=True, null=True, verbose_name='About this Series')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=40, verbose_name='Genre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='About Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(max_length=40, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubhouse', models.CharField(max_length=40, verbose_name='Publishing House')),
                ('otherbooks', models.TextField(blank=True, max_length=500, null=True, verbose_name='Other books of this house')),
            ],
        ),
    ]
