# Generated by Django 3.1.2 on 2020-12-02 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, default='User', max_length=20, null=True, verbose_name='Group')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile image')),
                ('phone_number', models.CharField(default='', max_length=35, verbose_name='Phone number')),
                ('country', models.CharField(default='', max_length=50, verbose_name='Country')),
                ('city', models.CharField(default='', max_length=50, verbose_name='City')),
                ('address', models.CharField(default='', max_length=50, verbose_name='First address')),
                ('index', models.CharField(default='', max_length=15, verbose_name='Index')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='CreditCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(blank=True, null=True, verbose_name='Card Number')),
                ('card_date', models.CharField(blank=True, max_length=5, null=True, verbose_name='Card date')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Name on the back')),
                ('cvv', models.PositiveIntegerField(blank=True, null=True, verbose_name='CVV')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_cards', to='user_auth.profile')),
            ],
            options={
                'verbose_name': 'Bank Card',
            },
        ),
    ]
